# Config from JoinEditLeave
# Made by JonaHD345 (http://github.com/JonaHD345)
# Support, bugs & ideas: discord: jonahd345 or contact@jonahd345.de
# Support PlaceholderAPI
# You can use '&' Colorcodes!

Config:
  Join: ''
  Leave: ''