# Config from JoinEditLeave
# Made by JonaHD345
# !!!WORKS ONLY WITH PLACEHODLERAPI!!!
# Support PlaceholderAPI
# You can use '&' Colorcodes!

Config:
  Join: ''
  Leave: ''


# Bugs or Ideas please via Discord: JonaHD345#0827